name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  generate_matrix:
    name: Set matrix
    runs-on: ubuntu-latest
    outputs:
      sdks: ${{ steps.out.outputs.sdks }}
    strategy:
      matrix:
        ref:
          - main # apk
          - openwrt-23.05 # ipk
    steps:
      - name: Checkout OpenWrt
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: ${{ matrix.ref }}

      - name: Set targets
        id: find_targets
        run: |
          REF=${{ matrix.ref }}

          JSON='['
          FIRST=1

          while read -r line;
          do
            ARCH=$(echo "$line" | cut -d " " -f 1)

            [[ $FIRST -ne 1 ]] && JSON="$JSON"','
            FIRST=0

            JSON="$JSON"'{"arch":"'"$ARCH"'","ref":"'"$REF"'"}'
          done <<< $(perl ./scripts/dump-target-info.pl architectures 2>/dev/null)

          JSON="$JSON"']'
          echo -e "\n---- sdks ----\n"
          echo "$JSON"
          echo -e "\n---- sdks ----\n"
          echo "sdks=$JSON" >> "$GITHUB_OUTPUT"

      - uses: cloudposse/github-action-matrix-outputs-write@main
        id: out
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.ref }}
          outputs: |-
            sdks: ${{ steps.find_targets.outputs.sdks }}

  gather_matrix:
    name: Gather build matrices
    runs-on: ubuntu-latest
    needs: generate_matrix
    outputs:
      result: ${{ steps.gather.outputs.result }}
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@main
        id: read
        with:
          matrix-step-name: generate_matrix
      - name: Gather matrices
        id: gather
        run: |
          result=$(jq -c '.sdks[]' <<< '${{ steps.read.outputs.result }}' | jq -c -s add)
          echo "result=${result}" >> $GITHUB_OUTPUT

  build:
    name: Build for ${{ matrix.arch }}-${{ matrix.ref }}
    runs-on: ubuntu-latest
    needs: gather_matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.gather_matrix.outputs.result) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Latest Cloudflared Version
        id: get_version
        run: |
          LATEST_VERSION=$(curl -sL https://api.github.com/repos/cloudflare/cloudflared/releases/latest | jq -r .tag_name)
          if [ -z "$LATEST_VERSION" ]; then
            echo "Failed to fetch latest version"
            exit 1
          fi
          echo "CLOUDFLARED_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Fetch and Patch Cloudflared Makefile
        run: |
          mkdir -p cloudflared
          curl -sL "https://raw.githubusercontent.com/openwrt/packages/master/net/cloudflared/Makefile" -o cloudflared/Makefile
          sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=${CLOUDFLARED_VERSION}/" cloudflared/Makefile
          sed -i "s/PKG_HASH:=.*/PKG_HASH:=skip/" cloudflared/Makefile
          sed -i 's#\.\./\.\.#$(TOPDIR)/feeds/packages#' cloudflared/Makefile

      - name: Create default files
        run: |
          mkdir -p cloudflared/files
          cat > cloudflared/files/sample_config.yml << 'EOF'
          tunnel: example-tunnel-id
          credentials-file: /etc/cloudflared/credentials.json

          #
          #ingress:
          #  - hostname: luci.example.com
          #    service: http://localhost:80
          #  - hostname: ssh.example.com
          #    service: ssh://localhost:22
          #  - service: http_status:404
          EOF
          cat > cloudflared/files/cloudflared.config << 'EOF'
          config cloudflared 'config'
              option enabled '0'
              option token ''
              option config '/etc/cloudflared/config.yml'
              option origincert '/etc/cloudflared/cert.pem'
              option protocol 'quic'
              option loglevel 'info'
              option logfile '/var/log/cloudflared.log'
          EOF
          cat > cloudflared/files/cloudflared.init << 'EOF'
          #!/bin/sh /etc/rc.common
          # Compiled by sludge <me@slud.ge>

          USE_PROCD=1
          START=99

          CONF="cloudflared"
          PROG="/usr/bin/cloudflared"

          append_param_arg() {
              local value
              config_get value "config" "$1" $2
              [ -n "$value" ] && procd_append_param command "--${1//_/-}" "$value"
          }

          start_service() {
              config_load "$CONF"

              local enabled
              config_get_bool enabled "config" "enabled"
              [ "$enabled" -eq "1" ] || return 1

              procd_open_instance "$CONF"
              procd_set_param command "$PROG" "tunnel"
              procd_append_param command "--no-autoupdate"

              append_param_arg "config" "/etc/cloudflared/config.yml"
              append_param_arg "origincert" "/etc/cloudflared/cert.pem"
              append_param_arg "edge_bind_address"
              append_param_arg "edge_ip_version"
              append_param_arg "grace_period"
              append_param_arg "protocol"
              append_param_arg "region"
              append_param_arg "retries"
              append_param_arg "tag"
              append_param_arg "metrics"
              append_param_arg "loglevel"
              append_param_arg "logfile"

              procd_append_param command "run"
              append_param_arg "token"

              procd_set_param respawn
              procd_set_param stderr 1

              procd_close_instance
          }

          reload_service() {
              stop
              start
          }

          service_triggers() {
              procd_add_reload_trigger "$CONF"
              procd_add_interface_trigger "interface.*.up" "wan" /etc/init.d/cloudflared restart
          }
          EOF
          chmod +x cloudflared/files/cloudflared.init

      - name: Build Package
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.ref }}
          V: s
          IGNORE_ERRORS: n m y

      - name: Append Architecture to APK Filename
        if: matrix.ref == 'main'
        working-directory: bin/packages/${{ matrix.arch }}
        run: |
          file=$(find . -name 'cloudflared*.apk')
          if [ -n "$file" ] && [[ "$file" != *${{ matrix.arch }}* ]]; then
            filename="${file%.*}"
            extension="${file##*.}"
            mv "$file" "$filename-${{ matrix.arch }}.$extension"
          fi

      - name: Upload Output Folder
        uses: actions/upload-artifact@v4
        with:
          name: cloudflared-${{ matrix.arch }}-${{ matrix.ref }}
          path: bin/packages/${{ matrix.arch }}/action/cloudflared*

  release:
    name: Release ${{ github.ref_name }}
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Generate SHA256 Sums
        run: |
          echo "## SHA256 Sums" > SUMS.md
          echo '```' >> SUMS.md
          for f in *.{apk,ipk}; do
            printf "%-55s %s\n" "$f" "$(sha256sum "$f" | cut -d' ' -f1)" >> SUMS.md
          done
          echo '```' >> SUMS.md

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: SUMS.md
          files: |
            *.apk
            *.ipk
